; AGS2 run script
; ---------------
;RunFile=A-Games:S/SWOSv11/SWOSv11.slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "S" "Sensible World of Soccer"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:S/SWOSv11/"
IF EXISTS ENV:whdloadargs
  whdload "SWOSv11.slave" $whdloadargs
ELSE
  whdload "SWOSv11.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
